name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential git

    - name: Download and build Raylib
      run: |
        git clone --branch=3.7.0 --depth=1 https://github.com/raysan5/raylib.git
        cd raylib
        make -j4
        sudo make install
        cd ..

    - name: Build
      run: make

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ github.sha }}
        release_name: Release ${{ github.sha }}
        draft: false
        prerelease: false

    - name: Upload Release Artifact
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: /path/to/your/release/artifact   # Update this path
        asset_name: your-release-artifact-name       # Update this name
        asset_content_type: application/zip          # Update content type
